Fix parsing of workflow command line arguments
Workflows expect that "$@" will not contain anything before the `--`
argument.  Fixes the following failure:
```
$ rear format -- /dev/sdb
ERROR: Argument 'format' not accepted. Use 'rear format -- --help' for more information.
```

Partially reverts commit a2fe977d3cac54e1dcdad49146f822217c2b83d1.

Related: https://github.com/rear/rear/pull/3500#issuecomment-3206558501