Fix parsing of workflow command line arguments (#3514)
In sbin/rear restore the ordering of the three parts
# Parse options
# Set workflow to first command line argument ...
# Keep the remaining command line arguments ...
which are handling command line options and arguments
to what it was initially before pull request 3500 was merged
because workflows expect that "$@" will not contain anything
before the '--' argument otherwise the following failure happens:
# rear format -- /dev/sdb
ERROR: Argument 'format' not accepted.