Increase default USB_UEFI_PART_SIZE from 100 to 200 MiB
100 MiB is too low. My first attempt to "rear -v mkrescue" an 64-bit kernel 4.9.11 fails with:
ERROR: Could not copy /tmp/rear.2wwzvo4iQ1W4LLK/tmp/initrd.cgz to /tmp/rear-efi.0sRzW//EFI/BOOT/initrd.cgz
Aborting due to an error, check /root/rear/var/log/rear/rear-d2.log for details.

The default 100 MiB is not a sensible value for an EFI boot partition nowadays:
# ls -lh /tmp/rear-efi.0sRzW/EFI/BOOT/
total 100M
-rwx------ 1 root root  79K Feb 22 22:59 BOOTX64.efi
-rwx------ 1 root root  96M Feb 22 22:59 initrd.cgz
-rwx------ 1 root root 4.7M Feb 19 14:49 kernel