Fix parsing of workflow command line arguments
Workflows expect that "$@" will not contain anything before the `--`
argument.  Fixes the following failure:
```
$ rear format -- /dev/sdb
ERROR: Argument 'format' not accepted. Use 'rear format -- --help' for more information.
```

Co-authored-by: Pavel Cahyna <pcahyna@redhat.com>
Fixes: a2fe977d3cac54e1dcdad49146f822217c2b83d1 ("In sbin/rear error out if '-c' is used in recovery system")
Related: https://github.com/rear/rear/pull/3500#issuecomment-3206558501